@baseUrl = http://localhost:5500
@coachToken = <pegar_token_de_sesion_clerk_del_coach>
@studentId = <uuid_del_estudiante>

DELETE {{baseUrl}}/api/students/{{studentId}}
Authorization: Bearer {{coachToken}}
