@baseUrl = http://localhost:5500/api
@token = {{login.response.body.data.token}}

### Login coach
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "coach@ejemplo.com",
  "password": "password123"
}

### Create plan
POST {{baseUrl}}/plans
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Plan Mensual Presencial",
  "description": "Acceso al gimnasio y seguimiento semanal",
  "amount": 49.99,
  "durationDays": 30,
  "isVirtual": false
}
