@baseUrl = http://localhost:5500/api
@token = {{login.response.body.data.token}}
@planId = <uuid_del_plan>

### Login coach
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "coach@ejemplo.com",
  "password": "password123"
}

### Update plan
PATCH {{baseUrl}}/plans/{{planId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Plan Mensual Presencial Plus",
  "amount": 59.99,
  "isActive": true
}
