@baseUrl = http://localhost:5500/api
@token = {{login.response.body.data.token}}

### Login student
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "alumno@ejemplo.com",
  "password": "newpassword123"
}

### Register fitness goals
POST {{baseUrl}}/me/onboarding/fitness-goals
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "trainingGoal": "MUSCLE_GAIN",
  "weeklyTrainingHours": 5,
  "budgetForNutrition": 150.00,
  "hasGymAccess": true,
  "trainsFromHome": false,
  "additionalInfo": "Quiero enfocarme en tren superior"
}

### Update fitness goals
PUT {{baseUrl}}/me/onboarding/fitness-goals
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "weeklyTrainingHours": 6,
  "trainsFromHome": true
}

### Get fitness goals
GET {{baseUrl}}/me/onboarding/fitness-goals
Authorization: Bearer {{token}}
