@baseUrl = http://localhost:5500/api

### Register coach
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "role": "COACH",
  "name": "Coach Demo",
  "email": "coach@ejemplo.com",
  "password": "password123"
}
